name: Build Docker image and push to Docker Hub

on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
       
      - name: Set date as tag
        id: date
        run: echo "::set-output name=DATE::$(TZ=Asia/Tokyo date +'%Y%m%d%H%M')"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.KUBERNETES_DOCKERHUB_USERNAME }}
          password: ${{ secrets.KUBERNETES_DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.KUBERNETES_DOCKERHUB_USERNAME }}/kubernetes-cicd:${{ steps.date.outputs.DATE }}

      - name: Change image
        run: |
          echo -e "machine github.com\nlogin ${{ secrets.KUBERNETES_GITHUBUSER }}\npassword ${{ secrets.KUBERNETES_GITHUBTOKEN }}" > ~/.netrc
          git config --global user.email "${{ secrets.KUBERNETES_EMAIL }}"
          git config --global user.name "${{ secrets.KUBERNETES_GITHUBUSER }}"
          git clone https://github.com/${{ secrets.KUBERNETES_GITHUBUSER }}/kubernetes-deploy.git

          cd kubernetes-deploy
          git checkout -b update-docker-image-${{ steps.date.outputs.DATE }}
          yq e '.spec.template.spec.containers[0].image = "${{ secrets.KUBERNETES_DOCKERHUB_USERNAME }}/kubernetes-cicd:${{ steps.date.outputs.DATE }}"' -i deployment.yaml
          git add deployment.yaml
          git commit -m "Update Docker image to ${{ steps.date.outputs.DATE }}"
          git push origin update-docker-image-${{ steps.date.outputs.DATE }}

          # Create a pull request using ghcommand
          gh pr create --base main --head update-docker-image-${{ steps.date.outputs.DATE }} --title "Update Docker image" --body "Update Docker image to ${{ steps.date.outputs.DATE }}"
        env:
          GH_TOKEN: ${{ secrets.KUBERNETES_GITHUBTOKEN }}
